name: Build and Deploy
on:
  release:
    types: [published]
jobs:
  deploy-to-dev:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Use Node.js 8
      uses: actions/setup-node@v3
      with:
          node-version: '8.x'
    - run: npm install
    - run: npm run build

#    - name: AWS credentials configuration
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-east-1
#
